// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whotmjndzgsjohiiyqsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indob3Rtam5kemdzam9oaWl5cXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTcwMjQsImV4cCI6MjA2ODkzMzAyNH0.R5oC5Q19rEdxpTWiOM4pS0-fcu95PXUJRS2RlJRByW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});